// Uncomment the code below and write your tests
// import { throwError, throwCustomError, resolveValue, MyAwesomeError, rejectCustomError } from './index';

describe('resolveValue', () => {
  test('should resolve provided value', async () => {});
});

describe('throwError', () => {
  test('should throw error with provided message', () => {});

  test('should throw error with default message if message is not provided', () => {});
});

describe('throwCustomError', () => {
  test('should throw custom error', () => {});
});

describe('rejectCustomError', () => {
  test('should reject custom error', async () => {});
});
